### ISSUE TITLE
Can't access settings page over vpn

### ISSUE THREAD

**Issue by flossgeek** [pssc/ha-addon-lms#19]
I'm trying to access the settings page of LMS on my tailscale IP, but I continuously get the error:
`403 Forbidden: settings/index.html `
I suspect it has to do with some sort of blockage. Is it possible to disable this?

**Comment by pssc** [comment]
@flossgeek nothing intentional and maybe I need to understand why and where is  generating the 403 error, is it lms or the nginx proxy for ingress... 

Is the VPN integrated in HA? 
This is via ingress not an iframe?
What skin are you using?
This been tested without the VPN? 
Which settings page to be specific?

direct access to port 9000 should still work

**Comment by flossgeek** [comment]
@pssc I can access the settings page through the home assistant ingress. Only when I try to reach it through a separate webpage (on port 9000) the error occurs. So I suspect it is a limitation of LMS, not your addon. You can close this issue if you want.

**Comment by pssc** [comment]
@flossgeek just tried over my VPN here and I have no issues, have you got a plugin installed that might me affecting this

**Comment by flossgeek** [comment]
No, it didn't work without any add-ons either. Perhaps because of the http connection? But I can access the settings page through the embedded Homeassistant UI, so it isn't really a problem for me.
